import PropTypes from 'prop-types';
import { noop } from 'lodash';

export const propTypes = {
    filterPhrase: PropTypes.string,
    userId: PropTypes.string,
    hideChat: PropTypes.func,
    resetCurrentChat: PropTypes.func,
    markChatAsRead: PropTypes.func,
    setFilterPhrase: PropTypes.func,
    getChats: PropTypes.func,
    getPreviousMessages: PropTypes.func,
    reset: PropTypes.func,
    showChatBtn: PropTypes.func,
    setTransferInitiatorIsChat: PropTypes.func,
    clearPreviousMessages: PropTypes.func,
    openChat: PropTypes.func,
    sendMoneyRequest: PropTypes.func,
    sendChatMessage: PropTypes.func,
    // функция для какой-либо инициализации
    initializeChat: PropTypes.func,
    setActiveChat: PropTypes.func,
    prevMsgLoading: PropTypes.bool,
    messagesLoading: PropTypes.bool,
    chatIsLoading: PropTypes.bool,
    reOpen: PropTypes.bool,
    chatsLoading: PropTypes.bool,
    sendMessageLoading: PropTypes.bool,
    sendMoneyRequestLoading: PropTypes.bool,
    botsLoading: PropTypes.bool,
    isLoggedIn: PropTypes.bool,
    // необходимо для внутренних целей
    opened: PropTypes.bool,
    messages: PropTypes.arrayOf(PropTypes.shape({})),
    chats: PropTypes.arrayOf(PropTypes.shape({})),
    commonChats: PropTypes.arrayOf(PropTypes.shape({})),
    supportChats: PropTypes.arrayOf(PropTypes.shape({})),
    currentChat: PropTypes.shape({}),

};

export const defaultProps = {
    resetCurrentChat: noop,
    reset: noop,
    markChatAsRead: noop,
    setFilterPhrase: noop,
    hideChat: noop,
    setTransferInitiatorIsChat: noop,
    clearPreviousMessages: noop,
    sendChatMessage: noop,
    getChats: noop,
    openChat: noop,
    showChatBtn: noop,
    initializeChat: noop,
    getPreviousMessages: noop,
    setActiveChat: noop,
    sendMoneyRequest: noop,
    prevMsgLoading: false,
    messagesLoading: false,
    sendMoneyRequestLoading: false,
    chatIsLoading: false,
    botsLoading: false,
    chatsLoading: false,
    reOpen: false,
    sendMessageLoading: false,
    opened: false,
    isLoggedIn: undefined,
    messages: undefined,
    userId: '',
    filterPhrase: '',
    currentChat: undefined,
    chats: [],
    commonChats: [],
    supportChats: [],
};
